wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.15.2
    framework: huggingface
    huggingface_version: 4.29.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685484034.596293
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.9.12
      5: 0.15.2
      6: 4.29.2
      8:
      - 5
batch_size:
  desc: null
  value: 1
gradient_accumulate_every:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0001
seq_len:
  desc: null
  value: 128
